import { chromium } from '@playwright/test'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1600, height: 800 } })
await page.goto('http://localhost:5188/paraiba-atlas/?pilar=gente&camada=gente.renda_per_capita&comparar=2507507,2503100,m2501,m2504')
await page.waitForTimeout(7000)
const box = await page.locator('section[aria-label="Comparação"]').boundingBox()
const scroller = page.locator('section[aria-label="Comparação"] div.overflow-auto')
const metrics = await scroller.evaluate((el) => ({ scrollHeight: el.scrollHeight, clientHeight: el.clientHeight, scrollable: el.scrollHeight > el.clientHeight }))
const closeVisible = await page.getByRole('button', { name: 'Fechar comparação' }).isVisible()
console.log(JSON.stringify({ sectionTop: Math.round(box.y), sectionHeight: Math.round(box.height), viewport: 800, ...metrics, closeVisible }))
await scroller.evaluate((el) => el.scrollTo(0, 0))
await page.waitForTimeout(400)
await page.locator('section[aria-label="Comparação"]').screenshot({ path: process.argv[2] })
await browser.close()
