import { chromium } from '@playwright/test'
const browser = await chromium.launch()
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true })
const page = await ctx.newPage()
await page.goto('http://localhost:5188/paraiba-atlas/')
await page.waitForTimeout(6500)
await page.getByRole('button', { expanded: false }).first().click()
await page.waitForTimeout(1500)
const before = await page.evaluate(() => ({ pitch: window.__atlasMap.getPitch(), terrain: !!window.__atlasMap.getTerrain(), zoom: +window.__atlasMap.getZoom().toFixed(2) }))
console.log('before', JSON.stringify(before))
await page.evaluate(() => { window.__atlasMap.setTerrain(null); window.__atlasMap.setPitch(0) })
await page.waitForTimeout(1500)
await page.screenshot({ path: process.argv[2] })
console.log('after ', JSON.stringify(await page.evaluate(() => ({ pitch: window.__atlasMap.getPitch(), terrain: !!window.__atlasMap.getTerrain() }))))
await browser.close()
