import { chromium } from '@playwright/test'
const browser = await chromium.launch()
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true })
const page = await ctx.newPage()
await page.goto('http://localhost:5188/paraiba-atlas/')
await page.waitForTimeout(6500)
await page.getByRole('button', { expanded: false }).first().click()
await page.waitForTimeout(1600)
await page.screenshot({ path: process.argv[2].replace('.png','-a-padded.png') })
await page.evaluate(() => window.__atlasMap.setPadding({ top: 0, bottom: 0, left: 0, right: 0 }))
await page.waitForTimeout(1200)
await page.screenshot({ path: process.argv[2].replace('.png','-b-nopad.png') })
await page.evaluate(() => { window.__atlasMap.resize(); window.__atlasMap.triggerRepaint() })
await page.waitForTimeout(1200)
await page.screenshot({ path: process.argv[2].replace('.png','-c-resized.png') })
await browser.close()
