import { chromium } from '@playwright/test'
const [url, lng, lat, out] = process.argv.slice(2)
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const errs = []
page.on('pageerror', (e) => errs.push(String(e).slice(0, 160)))
page.on('console', (m) => { if (m.type() === 'error') errs.push(m.text().slice(0, 160)) })
await page.goto(url)
await page.waitForTimeout(7000)
await page.evaluate(([lo, la]) => window.__atlasMap?.easeTo({ center: [Number(lo), Number(la)], zoom: 10, duration: 0 }), [lng, lat])
await page.waitForTimeout(2500)
const pt = await page.evaluate(([lo, la]) => window.__atlasMap?.project([Number(lo), Number(la)]), [lng, lat])
await page.mouse.click(pt.x, pt.y)
await page.waitForTimeout(1000)
const aside = page.locator('aside').first()
if (await aside.count()) await aside.screenshot({ path: out })
else await page.screenshot({ path: out })
console.log('errors:', JSON.stringify(errs.slice(0, 3)))
await browser.close()
