import { chromium } from '@playwright/test'
const browser = await chromium.launch()
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true })
const page = await ctx.newPage()
const errs = []
page.on('pageerror', (e) => errs.push(String(e).slice(0, 140)))
await page.goto(process.argv[2])
await page.waitForTimeout(6500)
await page.screenshot({ path: process.argv[3].replace('.png', '-closed.png') })
await page.getByRole('button', { expanded: false }).first().click()
await page.waitForTimeout(900)
await page.screenshot({ path: process.argv[3].replace('.png', '-open.png') })
await page.getByRole('button', { name: 'Gente', exact: true }).click()
await page.waitForTimeout(400)
await page.getByRole('button', { name: /Homicídios/ }).click()
await page.waitForTimeout(2500)
await page.screenshot({ path: process.argv[3].replace('.png', '-layer.png') })
console.log('errors:', JSON.stringify(errs))
await browser.close()
